import { Jost, Roboto } from 'next/font/google'

import './css/global.css';
import './css/vendors/animate.css';
import './css/vendors/splitting.css';
import './css/vendors/swiper.css';

export const metadata = {
	title: 'Vinod Kumar | vakadu',
	description: 'Generated by create-nx-workspace',
};

const jost = Jost({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-jost',
})
   
const roboto = Roboto({
	subsets: ['latin'],
	display: 'swap',
	variable: '--font-roboto',
	weight: ['300', '400', '500', '700'],
})

export default function RootLayout({
  	children,
}: {
  	children: React.ReactNode;
}) {
	return (
		<html lang="en" className={`${jost.variable} ${roboto.variable}`}>
			<body className='relative overflow-hidden min-h-[50vh]'>{children}</body>
		</html>
	);
}
